/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author emile
 */
public class Interfaz_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Vendedor
     */
    public Interfaz_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jDialog1 = new javax.swing.JDialog();
        Tabs = new javax.swing.JTabbedPane();
        Tab_Administrar = new javax.swing.JPanel();
        A_Productos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        A_BT_Productos_Crear = new javax.swing.JButton();
        A_BT_Productos_Modificar = new javax.swing.JButton();
        A_BT_Productos_Eliminar = new javax.swing.JButton();
        A_Tiendas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        A_BT_Tiendas_Eliminar = new javax.swing.JButton();
        A_BT_Tiendas_Modificar = new javax.swing.JButton();
        A_BT_Tiendas_Crear = new javax.swing.JButton();
        A_Clientes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        A_BT_Clientes_Eliminar = new javax.swing.JButton();
        A_BT_Clientes_Crear = new javax.swing.JButton();
        A_BT_Clientes_Modificar = new javax.swing.JButton();
        Tab_Tiendas = new javax.swing.JPanel();
        T_Panel_Botones = new javax.swing.JPanel();
        T_Decor_BarraSuperior = new javax.swing.JLabel();
        Decor_Sep_1 = new javax.swing.JSeparator();
        Decor_Sep_3 = new javax.swing.JSeparator();
        Decor_Sep_4 = new javax.swing.JSeparator();
        Decor_Sep_2 = new javax.swing.JSeparator();
        BT_1 = new javax.swing.JButton();
        BT_3 = new javax.swing.JButton();
        BT_4 = new javax.swing.JButton();
        BT_2 = new javax.swing.JButton();
        T_Decor_BarraSuperior1 = new javax.swing.JLabel();
        T_Panel_Inventario = new javax.swing.JPanel();
        Tab_Clientes = new javax.swing.JPanel();
        Tab_Productos = new javax.swing.JPanel();

        jDialog1.setMinimumSize(new java.awt.Dimension(700, 400));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(90, 50));
        setMinimumSize(new java.awt.Dimension(1362, 830));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        Tab_Administrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A_Productos.setBackground(new java.awt.Color(153, 0, 0));
        A_Productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos");
        jLabel1.setToolTipText("");
        A_Productos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1350, -1));

        A_BT_Productos_Crear.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Productos_Crear.setText("Crear");
        A_BT_Productos_Crear.setBorderPainted(false);
        A_Productos.add(A_BT_Productos_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 200, 130));

        A_BT_Productos_Modificar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Productos_Modificar.setText("Modificar");
        A_BT_Productos_Modificar.setBorderPainted(false);
        A_Productos.add(A_BT_Productos_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 200, 130));

        A_BT_Productos_Eliminar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Productos_Eliminar.setText("Eliminar");
        A_BT_Productos_Eliminar.setBorderPainted(false);
        A_Productos.add(A_BT_Productos_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 200, 130));

        Tab_Administrar.add(A_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1360, 270));

        A_Tiendas.setBackground(new java.awt.Color(102, 102, 0));
        A_Tiendas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tiendas");
        jLabel2.setToolTipText("");
        A_Tiendas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1350, -1));

        A_BT_Tiendas_Eliminar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Tiendas_Eliminar.setText("Eliminar");
        A_BT_Tiendas_Eliminar.setBorderPainted(false);
        A_Tiendas.add(A_BT_Tiendas_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 200, 130));

        A_BT_Tiendas_Modificar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Tiendas_Modificar.setText("Modificar");
        A_BT_Tiendas_Modificar.setBorderPainted(false);
        A_Tiendas.add(A_BT_Tiendas_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 200, 130));

        A_BT_Tiendas_Crear.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Tiendas_Crear.setText("Crear");
        A_BT_Tiendas_Crear.setBorderPainted(false);
        A_Tiendas.add(A_BT_Tiendas_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 200, 130));

        Tab_Administrar.add(A_Tiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 270));

        A_Clientes.setBackground(new java.awt.Color(0, 153, 0));
        A_Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Clientes");
        jLabel3.setToolTipText("");
        A_Clientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1350, -1));

        A_BT_Clientes_Eliminar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Clientes_Eliminar.setText("Eliminar");
        A_BT_Clientes_Eliminar.setBorderPainted(false);
        A_Clientes.add(A_BT_Clientes_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 200, 130));

        A_BT_Clientes_Crear.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Clientes_Crear.setText("Crear");
        A_BT_Clientes_Crear.setBorderPainted(false);
        A_Clientes.add(A_BT_Clientes_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 200, 130));

        A_BT_Clientes_Modificar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Clientes_Modificar.setText("Modificar");
        A_BT_Clientes_Modificar.setBorderPainted(false);
        A_Clientes.add(A_BT_Clientes_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 200, 130));

        Tab_Administrar.add(A_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1360, 270));

        Tabs.addTab("Administrar", Tab_Administrar);

        Tab_Tiendas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T_Panel_Botones.setBackground(new java.awt.Color(33, 33, 33));
        T_Panel_Botones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        T_Panel_Botones.add(T_Decor_BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1120, -1));

        Decor_Sep_1.setBackground(new java.awt.Color(0, 51, 102));
        Decor_Sep_1.setForeground(new java.awt.Color(0, 102, 255));
        Decor_Sep_1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Decor_Sep_1.setOpaque(true);
        T_Panel_Botones.add(Decor_Sep_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        Decor_Sep_3.setBackground(new java.awt.Color(0, 51, 102));
        Decor_Sep_3.setForeground(new java.awt.Color(0, 102, 255));
        Decor_Sep_3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Decor_Sep_3.setOpaque(true);
        T_Panel_Botones.add(Decor_Sep_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 10, 40));

        Decor_Sep_4.setBackground(new java.awt.Color(0, 51, 102));
        Decor_Sep_4.setForeground(new java.awt.Color(0, 102, 255));
        Decor_Sep_4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Decor_Sep_4.setOpaque(true);
        T_Panel_Botones.add(Decor_Sep_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 10, 40));

        Decor_Sep_2.setBackground(new java.awt.Color(0, 51, 102));
        Decor_Sep_2.setForeground(new java.awt.Color(0, 102, 255));
        Decor_Sep_2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Decor_Sep_2.setOpaque(true);
        T_Panel_Botones.add(Decor_Sep_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 10, 40));

        BT_1.setBackground(new java.awt.Color(33, 33, 33));
        BT_1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        BT_1.setForeground(new java.awt.Color(204, 204, 204));
        BT_1.setText("Crear");
        BT_1.setBorder(null);
        BT_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BT_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_1MousePressed(evt);
            }
        });
        BT_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_1ActionPerformed(evt);
            }
        });
        T_Panel_Botones.add(BT_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        BT_3.setBackground(new java.awt.Color(33, 33, 33));
        BT_3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        BT_3.setForeground(new java.awt.Color(204, 204, 204));
        BT_3.setText("B3");
        BT_3.setBorder(null);
        BT_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BT_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_3MousePressed(evt);
            }
        });
        T_Panel_Botones.add(BT_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 40));

        BT_4.setBackground(new java.awt.Color(33, 33, 33));
        BT_4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        BT_4.setForeground(new java.awt.Color(204, 204, 204));
        BT_4.setText("B4");
        BT_4.setBorder(null);
        BT_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BT_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_4MousePressed(evt);
            }
        });
        T_Panel_Botones.add(BT_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 40));

        BT_2.setBackground(new java.awt.Color(33, 33, 33));
        BT_2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        BT_2.setForeground(new java.awt.Color(204, 204, 204));
        BT_2.setText("B2");
        BT_2.setBorder(null);
        BT_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BT_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_2MousePressed(evt);
            }
        });
        BT_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_2ActionPerformed(evt);
            }
        });
        T_Panel_Botones.add(BT_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 40));
        T_Panel_Botones.add(T_Decor_BarraSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1120, 50));

        Tab_Tiendas.add(T_Panel_Botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 740));

        T_Panel_Inventario.setBackground(new java.awt.Color(204, 204, 255));
        T_Panel_Inventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Tab_Tiendas.add(T_Panel_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 1200, 740));

        Tabs.addTab("Tiendas", Tab_Tiendas);

        Tab_Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Tabs.addTab("Clientes", Tab_Clientes);

        Tab_Productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Tabs.addTab("Productos", Tab_Productos);

        getContentPane().add(Tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_2ActionPerformed

    }//GEN-LAST:event_BT_2ActionPerformed

    private void BT_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_2MousePressed

    }//GEN-LAST:event_BT_2MousePressed

    private void BT_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_4MousePressed

    }//GEN-LAST:event_BT_4MousePressed

    private void BT_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_3MousePressed

    }//GEN-LAST:event_BT_3MousePressed

    private void BT_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_1ActionPerformed

    }//GEN-LAST:event_BT_1ActionPerformed

    private void BT_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_1MousePressed
        /*
        T_ColorChange_Ventanas(BT_1, Decor_Sep_1,
            BT_3, BT_2, BT_4,
            Decor_Sep_2, Decor_Sep_3, Decor_Sep_4
        );
        BD_Visible_Panel1();
        */
    }//GEN-LAST:event_BT_1MousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_BT_Clientes_Crear;
    private javax.swing.JButton A_BT_Clientes_Eliminar;
    private javax.swing.JButton A_BT_Clientes_Modificar;
    private javax.swing.JButton A_BT_Productos_Crear;
    private javax.swing.JButton A_BT_Productos_Eliminar;
    private javax.swing.JButton A_BT_Productos_Modificar;
    private javax.swing.JButton A_BT_Tiendas_Crear;
    private javax.swing.JButton A_BT_Tiendas_Eliminar;
    private javax.swing.JButton A_BT_Tiendas_Modificar;
    private javax.swing.JPanel A_Clientes;
    private javax.swing.JPanel A_Productos;
    private javax.swing.JPanel A_Tiendas;
    private javax.swing.JButton BT_1;
    private javax.swing.JButton BT_2;
    private javax.swing.JButton BT_3;
    private javax.swing.JButton BT_4;
    private javax.swing.JSeparator Decor_Sep_1;
    private javax.swing.JSeparator Decor_Sep_2;
    private javax.swing.JSeparator Decor_Sep_3;
    private javax.swing.JSeparator Decor_Sep_4;
    private javax.swing.JLabel T_Decor_BarraSuperior;
    private javax.swing.JLabel T_Decor_BarraSuperior1;
    private javax.swing.JPanel T_Panel_Botones;
    private javax.swing.JPanel T_Panel_Inventario;
    private javax.swing.JPanel Tab_Administrar;
    private javax.swing.JPanel Tab_Clientes;
    private javax.swing.JPanel Tab_Productos;
    private javax.swing.JPanel Tab_Tiendas;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
