/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.util.Calendar;
import javax.swing.JDialog;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author emile
 */
public class Interfaz_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Vendedor
     */
    public Interfaz_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Crear_Tienda = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        TF_Nombre_CT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BT_Crear_CT = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        SP_HorarioApertura_CT = new javax.swing.JSpinner();
        SP_HorarioCierre_CT = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JD_Modificar_Tienda = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        TF_Nombre_MT = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        BT_Crear_CC2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        CB_Ubicacion_MT = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        SP_HorarioApertura_MT = new javax.swing.JSpinner();
        SP_HorarioCierre_MT = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        CB_Tienda_MT = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        JD_Modificar_Tienda_BG = new javax.swing.JLabel();
        JD_Eliminar_Tienda = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        BT_Eliminar_ET = new javax.swing.JButton();
        CB_Tienda_ET = new javax.swing.JComboBox<>();
        JD_Eliminar_Tienda_BG = new javax.swing.JLabel();
        JD_Crear_Cliente = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        TF_Correo_CC = new javax.swing.JTextField();
        TF_Nombre_CC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BT_Crear_CC = new javax.swing.JButton();
        JD_Crear_Cliente_BG = new javax.swing.JLabel();
        JD_Modificar_Cliente = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        TF_Correo_MC = new javax.swing.JTextField();
        TF_Nombre_MC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BT_Modificar_MC = new javax.swing.JButton();
        CB_Tienda_MT1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        JD_Modificar_Cliente_BG = new javax.swing.JLabel();
        JD_Eliminar_Cliente = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BT_Eliminar_EC = new javax.swing.JButton();
        CB_Cliente_EC = new javax.swing.JComboBox<>();
        JD_Crear_Producto = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        TF_Nombre_CP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        BT_Crear_CP = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        CB_Embalaje_CP = new javax.swing.JComboBox<>();
        TF_Size_CP = new javax.swing.JTextField();
        TF_Marca_CP = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        JD_Modificar_Producto = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        TF_Nombre_MP = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        BT_Modificar_MP = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        CB_Embalaje_MP = new javax.swing.JComboBox<>();
        TF_Size_MP = new javax.swing.JTextField();
        TF_Marca_MP = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        CB_Producto_MP = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        JD_Eliminar_Producto = new javax.swing.JDialog();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        BT_Eliminar_EP = new javax.swing.JButton();
        CB_Producto_EP = new javax.swing.JComboBox<>();
        Tabs = new javax.swing.JTabbedPane();
        Tab_Administrar = new javax.swing.JPanel();
        A_Productos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        A_BT_Crear_Productos = new javax.swing.JButton();
        A_BT_Modificar_Productos = new javax.swing.JButton();
        A_BT_Eliminar_Productos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        A_Productos_BG = new javax.swing.JLabel();
        A_Tiendas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        A_BT_Eliminar_Tiendas = new javax.swing.JButton();
        A_BT_Modificar_Tiendas = new javax.swing.JButton();
        A_BT_Crear_Tiendas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        A_Tiendas_BG = new javax.swing.JLabel();
        A_Clientes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        A_BT_Eliminar_Clientes = new javax.swing.JButton();
        A_BT_Crear_Clientes = new javax.swing.JButton();
        A_BT_Modificar_Clientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        A_Clientes_BG = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        Tab_Inventario = new javax.swing.JPanel();
        Decor_Panel_Inventario = new javax.swing.JLabel();
        Panel_Inventario = new javax.swing.JPanel();
        CB_Inventario = new javax.swing.JComboBox<>();
        TB_Inventario_Scrollpane = new javax.swing.JScrollPane();
        TB_Inventario = new javax.swing.JTable();
        TB_ProdMasVendidos_Scrollpane = new javax.swing.JScrollPane();
        TB_ProdMasVendidos = new javax.swing.JTable();
        JL_TiposMasVendidos_Scrollpane = new javax.swing.JScrollPane();
        JL_TiposMasVendidos = new javax.swing.JList<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Tab_HistorialVentas = new javax.swing.JPanel();
        Panel_HistorialVentas = new javax.swing.JPanel();
        CB_HistorialVentas = new javax.swing.JComboBox<>();
        TB_HistorialVentas_Scrollpane = new javax.swing.JScrollPane();
        TB_HistorialVentas = new javax.swing.JTable();
        JL_TiendasMasVentas_Scrollpane = new javax.swing.JScrollPane();
        JL_TiendasMasVentas = new javax.swing.JList<>();
        jLabel45 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        Decor_Panel_Ventas = new javax.swing.JLabel();
        Tab_VentasPais = new javax.swing.JPanel();
        Panel_VentaPais = new javax.swing.JPanel();
        CB_VentaPais = new javax.swing.JComboBox<>();
        TB_VentaPais_Scrollpane = new javax.swing.JScrollPane();
        TB_VentaPais = new javax.swing.JTable();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        Decor_Panel_VentaPais = new javax.swing.JLabel();
        Tab_Cliente = new javax.swing.JPanel();
        Panel_ComprasPorCliente = new javax.swing.JPanel();
        TF_ComprasPorCliente = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        CB_ComprasPorCliente_BuscarPor = new javax.swing.JComboBox<>();
        TB_ComprasPorCliente_Scrollpane = new javax.swing.JScrollPane();
        TB_ComprasPorCliente = new javax.swing.JTable();
        jLabel47 = new javax.swing.JLabel();
        Decor_Panel_Cliente = new javax.swing.JLabel();

        JD_Crear_Tienda.setResizable(false);
        JD_Crear_Tienda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Crear Tienda");
        JD_Crear_Tienda.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));
        JD_Crear_Tienda.getContentPane().add(TF_Nombre_CT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, -1));

        jLabel14.setText("Horario");
        JD_Crear_Tienda.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, 20));

        BT_Crear_CT.setText("Crear");
        JD_Crear_Tienda.getContentPane().add(BT_Crear_CT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 110, -1));

        jLabel20.setText("Nombre");
        JD_Crear_Tienda.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, 20));

        jLabel21.setText("Direccion:");
        JD_Crear_Tienda.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, 20));

        SP_HorarioApertura_CT.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1672552800000L), null, null, java.util.Calendar.HOUR));
        SP_HorarioApertura_CT.setToolTipText("");
        SP_HorarioApertura_CT.setEditor(new JSpinner.DateEditor(SP_HorarioApertura_CT, "hh:mm a"));
        JD_Crear_Tienda.getContentPane().add(SP_HorarioApertura_CT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 90, -1));
        new SpinnerDateModel(new java.util.Date(), null, null, Calendar.HOUR);

        SP_HorarioCierre_CT.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1672596000000L), null, null, java.util.Calendar.DAY_OF_MONTH));
        SP_HorarioCierre_CT.setEditor(new JSpinner.DateEditor(SP_HorarioCierre_CT, "hh:mm a")
        );
        JD_Crear_Tienda.getContentPane().add(SP_HorarioCierre_CT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 90, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("-");
        JD_Crear_Tienda.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 40, 20));

        jLabel51.setText("País:");
        JD_Crear_Tienda.getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 20));

        jLabel52.setText("Ciudad:");
        JD_Crear_Tienda.getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, 20));

        jLabel53.setText("Estado:");
        JD_Crear_Tienda.getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        JD_Crear_Tienda.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        JD_Modificar_Tienda.setResizable(false);
        JD_Modificar_Tienda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Modificar Tienda");
        JD_Modificar_Tienda.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));
        JD_Modificar_Tienda.getContentPane().add(TF_Nombre_MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 290, -1));

        jLabel23.setText("Horario");
        JD_Modificar_Tienda.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 20));

        BT_Crear_CC2.setText("Crear");
        JD_Modificar_Tienda.getContentPane().add(BT_Crear_CC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 110, -1));

        jLabel24.setText("Tienda");
        JD_Modificar_Tienda.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 20));

        CB_Ubicacion_MT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Modificar_Tienda.getContentPane().add(CB_Ubicacion_MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 190, -1));

        jLabel25.setText("Ubicación");
        JD_Modificar_Tienda.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 20));

        SP_HorarioApertura_MT.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1672552800000L), null, null, java.util.Calendar.HOUR));
        SP_HorarioApertura_MT.setToolTipText("");
        SP_HorarioApertura_MT.setEditor(new JSpinner.DateEditor(SP_HorarioApertura_MT, "hh:mm a"));
        JD_Modificar_Tienda.getContentPane().add(SP_HorarioApertura_MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 90, -1));
        new SpinnerDateModel(new java.util.Date(), null, null, Calendar.HOUR);

        SP_HorarioCierre_MT.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1672596000000L), null, null, java.util.Calendar.DAY_OF_MONTH));
        SP_HorarioCierre_MT.setEditor(new JSpinner.DateEditor(SP_HorarioCierre_MT, "hh:mm a")
        );
        JD_Modificar_Tienda.getContentPane().add(SP_HorarioCierre_MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 90, -1));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("-");
        JD_Modificar_Tienda.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 40, 20));

        CB_Tienda_MT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Modificar_Tienda.getContentPane().add(CB_Tienda_MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 290, -1));

        jLabel35.setText("Nombre");
        JD_Modificar_Tienda.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 20));
        JD_Modificar_Tienda.getContentPane().add(JD_Modificar_Tienda_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        JD_Eliminar_Tienda.setMinimumSize(new java.awt.Dimension(600, 300));
        JD_Eliminar_Tienda.setResizable(false);
        JD_Eliminar_Tienda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Eliminar Tienda");
        JD_Eliminar_Tienda.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));

        jLabel16.setText("Tienda");
        JD_Eliminar_Tienda.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        BT_Eliminar_ET.setText("Eliminar");
        JD_Eliminar_Tienda.getContentPane().add(BT_Eliminar_ET, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        CB_Tienda_ET.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Eliminar_Tienda.getContentPane().add(CB_Tienda_ET, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, -1));

        JD_Eliminar_Tienda_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JD_Eliminar_Tienda_BG.png"))); // NOI18N
        JD_Eliminar_Tienda.getContentPane().add(JD_Eliminar_Tienda_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        JD_Crear_Cliente.setResizable(false);
        JD_Crear_Cliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Crear Cliente");
        JD_Crear_Cliente.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));
        JD_Crear_Cliente.getContentPane().add(TF_Correo_CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 290, -1));
        JD_Crear_Cliente.getContentPane().add(TF_Nombre_CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, -1));

        jLabel5.setText("Correo Electrónico");
        JD_Crear_Cliente.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 20));

        jLabel6.setText("Nombre");
        JD_Crear_Cliente.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 20));

        BT_Crear_CC.setText("Crear");
        JD_Crear_Cliente.getContentPane().add(BT_Crear_CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));
        JD_Crear_Cliente.getContentPane().add(JD_Crear_Cliente_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        JD_Modificar_Cliente.setResizable(false);
        JD_Modificar_Cliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Modificar Cliente");
        JD_Modificar_Cliente.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));
        JD_Modificar_Cliente.getContentPane().add(TF_Correo_MC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 290, -1));
        JD_Modificar_Cliente.getContentPane().add(TF_Nombre_MC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 290, -1));

        jLabel8.setText("Correo Electrónico");
        JD_Modificar_Cliente.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 20));

        jLabel9.setText("Nombre");
        JD_Modificar_Cliente.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 20));

        BT_Modificar_MC.setText("Modificar");
        JD_Modificar_Cliente.getContentPane().add(BT_Modificar_MC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 110, -1));

        CB_Tienda_MT1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Modificar_Cliente.getContentPane().add(CB_Tienda_MT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 290, -1));

        jLabel36.setText("Tienda");
        JD_Modificar_Cliente.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 20));
        JD_Modificar_Cliente.getContentPane().add(JD_Modificar_Cliente_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        JD_Eliminar_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JD_Eliminar_Cliente.setMinimumSize(new java.awt.Dimension(600, 300));
        JD_Eliminar_Cliente.setResizable(false);
        JD_Eliminar_Cliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Eliminar Cliente");
        JD_Eliminar_Cliente.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));

        jLabel12.setText("Cliente");
        JD_Eliminar_Cliente.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        BT_Eliminar_EC.setText("Eliminar");
        JD_Eliminar_Cliente.getContentPane().add(BT_Eliminar_EC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        CB_Cliente_EC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Eliminar_Cliente.getContentPane().add(CB_Cliente_EC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, -1));

        JD_Crear_Producto.setMinimumSize(new java.awt.Dimension(600, 390));
        JD_Crear_Producto.setResizable(false);
        JD_Crear_Producto.setSize(new java.awt.Dimension(0, 0));
        JD_Crear_Producto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Crear Producto");
        JD_Crear_Producto.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));
        JD_Crear_Producto.getContentPane().add(TF_Nombre_CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, -1));

        jLabel18.setText("Embalaje");
        JD_Crear_Producto.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 20));

        BT_Crear_CP.setText("Crear");
        JD_Crear_Producto.getContentPane().add(BT_Crear_CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 110, -1));

        jLabel27.setText("Nombre");
        JD_Crear_Producto.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, 20));

        jLabel28.setText("Tamaño");
        JD_Crear_Producto.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 20));

        CB_Embalaje_CP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Crear_Producto.getContentPane().add(CB_Embalaje_CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 190, -1));
        JD_Crear_Producto.getContentPane().add(TF_Size_CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, -1));
        JD_Crear_Producto.getContentPane().add(TF_Marca_CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 190, -1));

        jLabel19.setText("Marca");
        JD_Crear_Producto.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, 20));

        JD_Modificar_Producto.setMinimumSize(new java.awt.Dimension(600, 430));
        JD_Modificar_Producto.setResizable(false);
        JD_Modificar_Producto.setSize(new java.awt.Dimension(0, 0));
        JD_Modificar_Producto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Modificar Producto");
        JD_Modificar_Producto.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));
        JD_Modificar_Producto.getContentPane().add(TF_Nombre_MP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 290, -1));

        jLabel30.setText("Embalaje");
        JD_Modificar_Producto.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 20));

        BT_Modificar_MP.setText("Modificar");
        JD_Modificar_Producto.getContentPane().add(BT_Modificar_MP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 110, -1));

        jLabel31.setText("Producto");
        JD_Modificar_Producto.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 50, 20));

        jLabel32.setText("Tamaño");
        JD_Modificar_Producto.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, 20));

        CB_Embalaje_MP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Modificar_Producto.getContentPane().add(CB_Embalaje_MP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 190, -1));
        JD_Modificar_Producto.getContentPane().add(TF_Size_MP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 190, -1));
        JD_Modificar_Producto.getContentPane().add(TF_Marca_MP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 190, -1));

        jLabel33.setText("Marca");
        JD_Modificar_Producto.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, 20));

        CB_Producto_MP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Modificar_Producto.getContentPane().add(CB_Producto_MP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 290, -1));

        jLabel34.setText("Nombre");
        JD_Modificar_Producto.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 20));

        JD_Eliminar_Producto.setMinimumSize(new java.awt.Dimension(600, 300));
        JD_Eliminar_Producto.setResizable(false);
        JD_Eliminar_Producto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Eliminar Producto");
        JD_Eliminar_Producto.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));

        jLabel38.setText("Producto");
        JD_Eliminar_Producto.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        BT_Eliminar_EP.setText("Eliminar");
        JD_Eliminar_Producto.getContentPane().add(BT_Eliminar_EP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        CB_Producto_EP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Eliminar_Producto.getContentPane().add(CB_Producto_EP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(90, 50));
        setMinimumSize(new java.awt.Dimension(1446, 830));
        setPreferredSize(new java.awt.Dimension(1446, 830));
        setResizable(false);

        Tabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        Tab_Administrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A_Productos.setBackground(new java.awt.Color(153, 0, 0));
        A_Productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 221, 170));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos");
        jLabel1.setToolTipText("");
        A_Productos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1360, 50));

        A_BT_Crear_Productos.setBackground(new java.awt.Color(29, 91, 49));
        A_BT_Crear_Productos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        A_BT_Crear_Productos.setText("Crear");
        A_BT_Crear_Productos.setBorderPainted(false);
        A_BT_Crear_Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_BT_Crear_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A_BT_Crear_ProductosMousePressed(evt);
            }
        });
        A_Productos.add(A_BT_Crear_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 280, 90));

        A_BT_Modificar_Productos.setBackground(new java.awt.Color(40, 77, 119));
        A_BT_Modificar_Productos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        A_BT_Modificar_Productos.setText("Modificar");
        A_BT_Modificar_Productos.setBorderPainted(false);
        A_BT_Modificar_Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_BT_Modificar_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A_BT_Modificar_ProductosMousePressed(evt);
            }
        });
        A_Productos.add(A_BT_Modificar_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 280, 90));

        A_BT_Eliminar_Productos.setBackground(new java.awt.Color(99, 32, 39));
        A_BT_Eliminar_Productos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        A_BT_Eliminar_Productos.setText("Eliminar");
        A_BT_Eliminar_Productos.setBorderPainted(false);
        A_BT_Eliminar_Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_BT_Eliminar_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A_BT_Eliminar_ProductosMousePressed(evt);
            }
        });
        A_Productos.add(A_BT_Eliminar_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 280, 90));

        jSeparator3.setBackground(new java.awt.Color(170, 86, 0));
        jSeparator3.setForeground(new java.awt.Color(198, 144, 102));
        jSeparator3.setOpaque(true);
        A_Productos.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 240, 10));

        A_Productos_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/A_Productos_BG.jpg"))); // NOI18N
        A_Productos.add(A_Productos_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 270));

        Tab_Administrar.add(A_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1360, 270));

        A_Tiendas.setBackground(new java.awt.Color(102, 102, 0));
        A_Tiendas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(216, 170, 170));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tiendas");
        jLabel2.setToolTipText("");
        A_Tiendas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1360, -1));

        A_BT_Eliminar_Tiendas.setBackground(new java.awt.Color(99, 32, 39));
        A_BT_Eliminar_Tiendas.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        A_BT_Eliminar_Tiendas.setText("Eliminar");
        A_BT_Eliminar_Tiendas.setBorderPainted(false);
        A_BT_Eliminar_Tiendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_BT_Eliminar_Tiendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A_BT_Eliminar_TiendasMousePressed(evt);
            }
        });
        A_Tiendas.add(A_BT_Eliminar_Tiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 280, 90));

        A_BT_Modificar_Tiendas.setBackground(new java.awt.Color(40, 77, 119));
        A_BT_Modificar_Tiendas.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        A_BT_Modificar_Tiendas.setText("Modificar");
        A_BT_Modificar_Tiendas.setBorderPainted(false);
        A_BT_Modificar_Tiendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_BT_Modificar_Tiendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A_BT_Modificar_TiendasMousePressed(evt);
            }
        });
        A_Tiendas.add(A_BT_Modificar_Tiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 280, 90));

        A_BT_Crear_Tiendas.setBackground(new java.awt.Color(29, 91, 49));
        A_BT_Crear_Tiendas.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        A_BT_Crear_Tiendas.setText("Crear");
        A_BT_Crear_Tiendas.setBorderPainted(false);
        A_BT_Crear_Tiendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_BT_Crear_Tiendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A_BT_Crear_TiendasMousePressed(evt);
            }
        });
        A_Tiendas.add(A_BT_Crear_Tiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 280, 90));

        jSeparator2.setBackground(new java.awt.Color(86, 35, 35));
        jSeparator2.setForeground(new java.awt.Color(198, 139, 139));
        jSeparator2.setOpaque(true);
        A_Tiendas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 240, 10));

        A_Tiendas_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/A_Tiendas_BG.jpg"))); // NOI18N
        A_Tiendas.add(A_Tiendas_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 270));

        Tab_Administrar.add(A_Tiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 270));

        A_Clientes.setBackground(new java.awt.Color(0, 153, 0));
        A_Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Clientes");
        jLabel3.setToolTipText("");
        A_Clientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1350, -1));

        A_BT_Eliminar_Clientes.setBackground(new java.awt.Color(99, 32, 39));
        A_BT_Eliminar_Clientes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        A_BT_Eliminar_Clientes.setText("Eliminar");
        A_BT_Eliminar_Clientes.setBorderPainted(false);
        A_BT_Eliminar_Clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_BT_Eliminar_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A_BT_Eliminar_ClientesMousePressed(evt);
            }
        });
        A_Clientes.add(A_BT_Eliminar_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 280, 90));

        A_BT_Crear_Clientes.setBackground(new java.awt.Color(29, 91, 49));
        A_BT_Crear_Clientes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        A_BT_Crear_Clientes.setText("Crear");
        A_BT_Crear_Clientes.setBorderPainted(false);
        A_BT_Crear_Clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_BT_Crear_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A_BT_Crear_ClientesMousePressed(evt);
            }
        });
        A_Clientes.add(A_BT_Crear_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 280, 90));

        A_BT_Modificar_Clientes.setBackground(new java.awt.Color(40, 77, 119));
        A_BT_Modificar_Clientes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        A_BT_Modificar_Clientes.setText("Modificar");
        A_BT_Modificar_Clientes.setBorderPainted(false);
        A_BT_Modificar_Clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_BT_Modificar_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A_BT_Modificar_ClientesMousePressed(evt);
            }
        });
        A_Clientes.add(A_BT_Modificar_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 280, 90));

        jSeparator1.setBackground(new java.awt.Color(45, 41, 32));
        jSeparator1.setForeground(new java.awt.Color(198, 179, 139));
        jSeparator1.setOpaque(true);
        A_Clientes.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 240, 10));

        A_Clientes_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/A_Clientes_BG.jpg"))); // NOI18N
        A_Clientes.add(A_Clientes_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 270));

        Tab_Administrar.add(A_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1360, 270));

        jLabel49.setBackground(new java.awt.Color(61, 26, 31));
        jLabel49.setForeground(new java.awt.Color(151, 169, 187));
        jLabel49.setOpaque(true);
        Tab_Administrar.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1360, 310));

        Tabs.addTab("Administrar", Tab_Administrar);

        Tab_Inventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Decor_Panel_Inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Decor_Panel_Inventario.setText("Inventario");
        Tab_Inventario.add(Decor_Panel_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 100));

        Panel_Inventario.setBackground(new java.awt.Color(69, 69, 86));
        Panel_Inventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Inventario.add(CB_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 380, -1));

        TB_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "UPC", "Nombre", "Precio", "Cantidad", "Reorden"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB_Inventario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TB_Inventario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TB_Inventario.setShowGrid(true);
        TB_Inventario.getTableHeader().setReorderingAllowed(false);
        TB_Inventario.setUpdateSelectionOnSort(false);
        TB_Inventario_Scrollpane.setViewportView(TB_Inventario);

        Panel_Inventario.add(TB_Inventario_Scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 750, 580));

        TB_ProdMasVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "UPC", "Nombre", "Marca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB_ProdMasVendidos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TB_ProdMasVendidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TB_ProdMasVendidos.setShowGrid(true);
        TB_ProdMasVendidos.getTableHeader().setReorderingAllowed(false);
        TB_ProdMasVendidos.setUpdateSelectionOnSort(false);
        TB_ProdMasVendidos_Scrollpane.setViewportView(TB_ProdMasVendidos);

        Panel_Inventario.add(TB_ProdMasVendidos_Scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 340, 560));

        JL_TiposMasVendidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tipo Producto 1", "Tipo Producto 2", "Tipo Producto 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JL_TiposMasVendidos_Scrollpane.setViewportView(JL_TiposMasVendidos);

        Panel_Inventario.add(JL_TiposMasVendidos_Scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 110, 210, 140));

        jLabel40.setText("Tienda");
        Panel_Inventario.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 60, 20));

        jLabel41.setBackground(new java.awt.Color(61, 72, 74));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Inventario");
        jLabel41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jLabel41.setOpaque(true);
        Panel_Inventario.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 750, 20));

        jLabel42.setBackground(new java.awt.Color(61, 72, 74));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Productos más vendidos en la tienda");
        jLabel42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jLabel42.setOpaque(true);
        Panel_Inventario.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 340, 20));

        jLabel43.setBackground(new java.awt.Color(61, 72, 74));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Tipos de productos más vendidos");
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabel43.setOpaque(true);
        Panel_Inventario.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 210, 20));

        Tab_Inventario.add(Panel_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1360, 730));

        Tabs.addTab("Inventario", Tab_Inventario);

        Tab_HistorialVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_HistorialVentas.setBackground(new java.awt.Color(153, 0, 51));
        Panel_HistorialVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CB_HistorialVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_HistorialVentasActionPerformed(evt);
            }
        });
        Panel_HistorialVentas.add(CB_HistorialVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 380, -1));

        TB_HistorialVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TB_HistorialVentas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TB_HistorialVentas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TB_HistorialVentas.setShowGrid(true);
        TB_HistorialVentas.setUpdateSelectionOnSort(false);
        TB_HistorialVentas_Scrollpane.setViewportView(TB_HistorialVentas);

        Panel_HistorialVentas.add(TB_HistorialVentas_Scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1070, 580));

        JL_TiendasMasVentas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tienda 1", "Tienda 2", "Tienda 3", "Tienda 4", "Tienda 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JL_TiendasMasVentas_Scrollpane.setViewportView(JL_TiendasMasVentas);

        Panel_HistorialVentas.add(JL_TiendasMasVentas_Scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1112, 90, 220, 140));

        jLabel45.setText("Tienda");
        Panel_HistorialVentas.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 40, 20));

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Tiendas con más ventas en el año");
        Panel_HistorialVentas.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 220, -1));

        jLabel46.setBackground(new java.awt.Color(61, 72, 74));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Ventas");
        jLabel46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jLabel46.setOpaque(true);
        Panel_HistorialVentas.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1070, 20));

        Tab_HistorialVentas.add(Panel_HistorialVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1360, 730));

        Decor_Panel_Ventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Decor_Panel_Ventas.setText("Historial de ventas por tienda");
        Tab_HistorialVentas.add(Decor_Panel_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 100));

        Tabs.addTab("Ventas", Tab_HistorialVentas);

        Tab_VentasPais.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_VentaPais.setBackground(new java.awt.Color(91, 79, 43));
        Panel_VentaPais.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CB_VentaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_VentaPaisActionPerformed(evt);
            }
        });
        Panel_VentaPais.add(CB_VentaPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 380, -1));

        TB_VentaPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "UPC", "Nombre", "Tamaño", "Embalaje", "Marca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB_VentaPais.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TB_VentaPais.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TB_VentaPais.setShowGrid(true);
        TB_VentaPais.getTableHeader().setReorderingAllowed(false);
        TB_VentaPais.setUpdateSelectionOnSort(false);
        TB_VentaPais_Scrollpane.setViewportView(TB_VentaPais);

        Panel_VentaPais.add(TB_VentaPais_Scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1320, 580));

        jLabel48.setText("País");
        Panel_VentaPais.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 40, 20));

        jLabel50.setBackground(new java.awt.Color(61, 72, 74));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Productos");
        jLabel50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jLabel50.setOpaque(true);
        Panel_VentaPais.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1320, 20));

        Tab_VentasPais.add(Panel_VentaPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1360, 730));

        Decor_Panel_VentaPais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Decor_Panel_VentaPais.setText("Productos más vendidos por país");
        Tab_VentasPais.add(Decor_Panel_VentaPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 100));

        Tabs.addTab("País", Tab_VentasPais);

        Tab_Cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_ComprasPorCliente.setBackground(new java.awt.Color(0, 102, 102));
        Panel_ComprasPorCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_ComprasPorCliente.add(TF_ComprasPorCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 280, -1));

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Buscar por");
        Panel_ComprasPorCliente.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 70, -1));

        CB_ComprasPorCliente_BuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre" }));
        CB_ComprasPorCliente_BuscarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_ComprasPorCliente_BuscarPorActionPerformed(evt);
            }
        });
        Panel_ComprasPorCliente.add(CB_ComprasPorCliente_BuscarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        TB_ComprasPorCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre Cliente", "Correo Electrónico", "Fecha Compra", "ISV", "Subtotal", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB_ComprasPorCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TB_ComprasPorCliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TB_ComprasPorCliente.setShowGrid(true);
        TB_ComprasPorCliente.getTableHeader().setReorderingAllowed(false);
        TB_ComprasPorCliente.setUpdateSelectionOnSort(false);
        TB_ComprasPorCliente_Scrollpane.setViewportView(TB_ComprasPorCliente);

        Panel_ComprasPorCliente.add(TB_ComprasPorCliente_Scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1320, 550));

        jLabel47.setBackground(new java.awt.Color(61, 72, 74));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Compras");
        jLabel47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jLabel47.setOpaque(true);
        Panel_ComprasPorCliente.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1320, 20));

        Tab_Cliente.add(Panel_ComprasPorCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1360, 730));

        Decor_Panel_Cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Decor_Panel_Cliente.setText("Historial de compras por cliente");
        Tab_Cliente.add(Decor_Panel_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 100));

        Tabs.addTab("Cliente", Tab_Cliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1446, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_BT_Crear_ProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_BT_Crear_ProductosMousePressed
        Abrir_JDialog(JD_Crear_Producto);
    }//GEN-LAST:event_A_BT_Crear_ProductosMousePressed

    private void A_BT_Modificar_ProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_BT_Modificar_ProductosMousePressed
        Abrir_JDialog(JD_Modificar_Producto);
    }//GEN-LAST:event_A_BT_Modificar_ProductosMousePressed

    private void A_BT_Eliminar_ProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_BT_Eliminar_ProductosMousePressed
        Abrir_JDialog(JD_Eliminar_Producto);
    }//GEN-LAST:event_A_BT_Eliminar_ProductosMousePressed

    private void A_BT_Eliminar_TiendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_BT_Eliminar_TiendasMousePressed
        Abrir_JDialog(JD_Eliminar_Tienda);
    }//GEN-LAST:event_A_BT_Eliminar_TiendasMousePressed

    private void A_BT_Modificar_TiendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_BT_Modificar_TiendasMousePressed
        Abrir_JDialog(JD_Modificar_Tienda);
    }//GEN-LAST:event_A_BT_Modificar_TiendasMousePressed

    private void A_BT_Crear_TiendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_BT_Crear_TiendasMousePressed
        Abrir_JDialog(JD_Crear_Tienda);
    }//GEN-LAST:event_A_BT_Crear_TiendasMousePressed

    private void A_BT_Eliminar_ClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_BT_Eliminar_ClientesMousePressed
        Abrir_JDialog(JD_Eliminar_Cliente);
    }//GEN-LAST:event_A_BT_Eliminar_ClientesMousePressed

    private void A_BT_Crear_ClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_BT_Crear_ClientesMousePressed
        Abrir_JDialog(JD_Crear_Cliente);
    }//GEN-LAST:event_A_BT_Crear_ClientesMousePressed

    private void A_BT_Modificar_ClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_BT_Modificar_ClientesMousePressed
        Abrir_JDialog(JD_Modificar_Cliente);
    }//GEN-LAST:event_A_BT_Modificar_ClientesMousePressed

    private void CB_HistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_HistorialVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_HistorialVentasActionPerformed

    private void CB_VentaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_VentaPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_VentaPaisActionPerformed

    private void CB_ComprasPorCliente_BuscarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_ComprasPorCliente_BuscarPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_ComprasPorCliente_BuscarPorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_BT_Crear_Clientes;
    private javax.swing.JButton A_BT_Crear_Productos;
    private javax.swing.JButton A_BT_Crear_Tiendas;
    private javax.swing.JButton A_BT_Eliminar_Clientes;
    private javax.swing.JButton A_BT_Eliminar_Productos;
    private javax.swing.JButton A_BT_Eliminar_Tiendas;
    private javax.swing.JButton A_BT_Modificar_Clientes;
    private javax.swing.JButton A_BT_Modificar_Productos;
    private javax.swing.JButton A_BT_Modificar_Tiendas;
    private javax.swing.JPanel A_Clientes;
    private javax.swing.JLabel A_Clientes_BG;
    private javax.swing.JPanel A_Productos;
    private javax.swing.JLabel A_Productos_BG;
    private javax.swing.JPanel A_Tiendas;
    private javax.swing.JLabel A_Tiendas_BG;
    private javax.swing.JButton BT_Crear_CC;
    private javax.swing.JButton BT_Crear_CC2;
    private javax.swing.JButton BT_Crear_CP;
    private javax.swing.JButton BT_Crear_CT;
    private javax.swing.JButton BT_Eliminar_EC;
    private javax.swing.JButton BT_Eliminar_EP;
    private javax.swing.JButton BT_Eliminar_ET;
    private javax.swing.JButton BT_Modificar_MC;
    private javax.swing.JButton BT_Modificar_MP;
    private javax.swing.JComboBox<String> CB_Cliente_EC;
    private javax.swing.JComboBox<String> CB_ComprasPorCliente_BuscarPor;
    private javax.swing.JComboBox<String> CB_Embalaje_CP;
    private javax.swing.JComboBox<String> CB_Embalaje_MP;
    private javax.swing.JComboBox<String> CB_HistorialVentas;
    private javax.swing.JComboBox<String> CB_Inventario;
    private javax.swing.JComboBox<String> CB_Producto_EP;
    private javax.swing.JComboBox<String> CB_Producto_MP;
    private javax.swing.JComboBox<String> CB_Tienda_ET;
    private javax.swing.JComboBox<String> CB_Tienda_MT;
    private javax.swing.JComboBox<String> CB_Tienda_MT1;
    private javax.swing.JComboBox<String> CB_Ubicacion_MT;
    private javax.swing.JComboBox<String> CB_VentaPais;
    private javax.swing.JLabel Decor_Panel_Cliente;
    private javax.swing.JLabel Decor_Panel_Inventario;
    private javax.swing.JLabel Decor_Panel_VentaPais;
    private javax.swing.JLabel Decor_Panel_Ventas;
    private javax.swing.JDialog JD_Crear_Cliente;
    private javax.swing.JLabel JD_Crear_Cliente_BG;
    private javax.swing.JDialog JD_Crear_Producto;
    private javax.swing.JDialog JD_Crear_Tienda;
    private javax.swing.JDialog JD_Eliminar_Cliente;
    private javax.swing.JDialog JD_Eliminar_Producto;
    private javax.swing.JDialog JD_Eliminar_Tienda;
    private javax.swing.JLabel JD_Eliminar_Tienda_BG;
    private javax.swing.JDialog JD_Modificar_Cliente;
    private javax.swing.JLabel JD_Modificar_Cliente_BG;
    private javax.swing.JDialog JD_Modificar_Producto;
    private javax.swing.JDialog JD_Modificar_Tienda;
    private javax.swing.JLabel JD_Modificar_Tienda_BG;
    private javax.swing.JList<String> JL_TiendasMasVentas;
    private javax.swing.JScrollPane JL_TiendasMasVentas_Scrollpane;
    private javax.swing.JList<String> JL_TiposMasVendidos;
    private javax.swing.JScrollPane JL_TiposMasVendidos_Scrollpane;
    private javax.swing.JPanel Panel_ComprasPorCliente;
    private javax.swing.JPanel Panel_HistorialVentas;
    private javax.swing.JPanel Panel_Inventario;
    private javax.swing.JPanel Panel_VentaPais;
    private javax.swing.JSpinner SP_HorarioApertura_CT;
    private javax.swing.JSpinner SP_HorarioApertura_MT;
    private javax.swing.JSpinner SP_HorarioCierre_CT;
    private javax.swing.JSpinner SP_HorarioCierre_MT;
    private javax.swing.JTable TB_ComprasPorCliente;
    private javax.swing.JScrollPane TB_ComprasPorCliente_Scrollpane;
    private javax.swing.JTable TB_HistorialVentas;
    private javax.swing.JScrollPane TB_HistorialVentas_Scrollpane;
    private javax.swing.JTable TB_Inventario;
    private javax.swing.JScrollPane TB_Inventario_Scrollpane;
    private javax.swing.JTable TB_ProdMasVendidos;
    private javax.swing.JScrollPane TB_ProdMasVendidos_Scrollpane;
    private javax.swing.JTable TB_VentaPais;
    private javax.swing.JScrollPane TB_VentaPais_Scrollpane;
    private javax.swing.JTextField TF_ComprasPorCliente;
    private javax.swing.JTextField TF_Correo_CC;
    private javax.swing.JTextField TF_Correo_MC;
    private javax.swing.JTextField TF_Marca_CP;
    private javax.swing.JTextField TF_Marca_MP;
    private javax.swing.JTextField TF_Nombre_CC;
    private javax.swing.JTextField TF_Nombre_CP;
    private javax.swing.JTextField TF_Nombre_CT;
    private javax.swing.JTextField TF_Nombre_MC;
    private javax.swing.JTextField TF_Nombre_MP;
    private javax.swing.JTextField TF_Nombre_MT;
    private javax.swing.JTextField TF_Size_CP;
    private javax.swing.JTextField TF_Size_MP;
    private javax.swing.JPanel Tab_Administrar;
    private javax.swing.JPanel Tab_Cliente;
    private javax.swing.JPanel Tab_HistorialVentas;
    private javax.swing.JPanel Tab_Inventario;
    private javax.swing.JPanel Tab_VentasPais;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    public void Abrir_JDialog(JDialog JD) {
        JD.setModal(true);
        JD.pack();
        JD.setLocationRelativeTo(null);//this Frame
        JD.setVisible(true);
    }

}
