/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.util.Calendar;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
/**
 *
 * @author emile
 */
public class Interfaz_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Vendedor
     */
    public Interfaz_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Crear_Cliente = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        TF_Correo_CC = new javax.swing.JTextField();
        TF_Nombre_CC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BT_Crear_CC = new javax.swing.JButton();
        JD_Modificar_Cliente = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        TF_Correo_MC = new javax.swing.JTextField();
        TF_Nombre_MC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BT_Modificar_MC = new javax.swing.JButton();
        JD_Eliminar_Cliente = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BT_Eliminar_EC = new javax.swing.JButton();
        CB_Cliente_EC = new javax.swing.JComboBox<>();
        JD_Crear_Tienda = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        TF_Nombre_CT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BT_Crear_CC1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        CB_Ubicacion_CT = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        SP_HorarioApertura_CT = new javax.swing.JSpinner();
        SP_HorarioCierre_CT = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        JD_Modificar_Tienda = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        TF_Nombre_MT = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        BT_Crear_CC2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        CB_Ubicacion_MT = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        SP_HorarioApertura_MT = new javax.swing.JSpinner();
        SP_HorarioCierre_MT = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        JD_Eliminar_Tienda = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        BT_Eliminar_ET = new javax.swing.JButton();
        CB_Tienda_ET = new javax.swing.JComboBox<>();
        Tabs = new javax.swing.JTabbedPane();
        Tab_Administrar = new javax.swing.JPanel();
        A_Productos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        A_BT_Crear_Productos = new javax.swing.JButton();
        A_BT_Modificar_Productos = new javax.swing.JButton();
        A_BT_Eliminar_Productos = new javax.swing.JButton();
        A_Tiendas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        A_BT_Eliminar_Tiendas = new javax.swing.JButton();
        A_BT_Modificar_Tiendas = new javax.swing.JButton();
        A_BT_Crear_Tiendas = new javax.swing.JButton();
        A_Clientes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        A_BT_Eliminar_Clientes = new javax.swing.JButton();
        A_BT_Crear_Clientes = new javax.swing.JButton();
        A_BT_Modificar_Clientes = new javax.swing.JButton();
        Tab_Tiendas = new javax.swing.JPanel();
        T_Panel_Botones = new javax.swing.JPanel();
        T_Decor_BarraSuperior = new javax.swing.JLabel();
        Decor_Sep_1 = new javax.swing.JSeparator();
        Decor_Sep_3 = new javax.swing.JSeparator();
        Decor_Sep_4 = new javax.swing.JSeparator();
        Decor_Sep_2 = new javax.swing.JSeparator();
        BT_1 = new javax.swing.JButton();
        BT_3 = new javax.swing.JButton();
        BT_4 = new javax.swing.JButton();
        BT_2 = new javax.swing.JButton();
        T_Decor_BarraSuperior1 = new javax.swing.JLabel();
        T_Panel_Inventario = new javax.swing.JPanel();
        Tab_Clientes = new javax.swing.JPanel();
        Tab_Productos = new javax.swing.JPanel();

        JD_Crear_Cliente.setMinimumSize(new java.awt.Dimension(600, 300));
        JD_Crear_Cliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Crear Cliente");
        JD_Crear_Cliente.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));
        JD_Crear_Cliente.getContentPane().add(TF_Correo_CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 290, -1));
        JD_Crear_Cliente.getContentPane().add(TF_Nombre_CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, -1));

        jLabel5.setText("Correo Electrónico");
        JD_Crear_Cliente.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 20));

        jLabel6.setText("Nombre");
        JD_Crear_Cliente.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 20));

        BT_Crear_CC.setText("Crear");
        JD_Crear_Cliente.getContentPane().add(BT_Crear_CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        JD_Modificar_Cliente.setMinimumSize(new java.awt.Dimension(600, 300));
        JD_Modificar_Cliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Modificar Cliente");
        JD_Modificar_Cliente.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));
        JD_Modificar_Cliente.getContentPane().add(TF_Correo_MC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 290, -1));
        JD_Modificar_Cliente.getContentPane().add(TF_Nombre_MC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, -1));

        jLabel8.setText("Correo Electrónico");
        JD_Modificar_Cliente.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 20));

        jLabel9.setText("Nombre");
        JD_Modificar_Cliente.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 20));

        BT_Modificar_MC.setText("Modificar");
        JD_Modificar_Cliente.getContentPane().add(BT_Modificar_MC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        JD_Eliminar_Cliente.setMinimumSize(new java.awt.Dimension(600, 300));
        JD_Eliminar_Cliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Eliminar Cliente");
        JD_Eliminar_Cliente.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));

        jLabel12.setText("Cliente");
        JD_Eliminar_Cliente.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        BT_Eliminar_EC.setText("Eliminar");
        JD_Eliminar_Cliente.getContentPane().add(BT_Eliminar_EC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        CB_Cliente_EC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Eliminar_Cliente.getContentPane().add(CB_Cliente_EC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, -1));

        JD_Crear_Tienda.setMinimumSize(new java.awt.Dimension(600, 340));
        JD_Crear_Tienda.setResizable(false);
        JD_Crear_Tienda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Crear Tienda");
        JD_Crear_Tienda.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));
        JD_Crear_Tienda.getContentPane().add(TF_Nombre_CT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, -1));

        jLabel14.setText("Horario");
        JD_Crear_Tienda.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, 20));

        BT_Crear_CC1.setText("Crear");
        JD_Crear_Tienda.getContentPane().add(BT_Crear_CC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 110, -1));

        jLabel20.setText("Nombre");
        JD_Crear_Tienda.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, 20));

        CB_Ubicacion_CT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Crear_Tienda.getContentPane().add(CB_Ubicacion_CT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, -1));

        jLabel21.setText("Ubicación");
        JD_Crear_Tienda.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 20));

        SP_HorarioApertura_CT.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1672552800000L), null, null, java.util.Calendar.HOUR));
        SP_HorarioApertura_CT.setToolTipText("");
        SP_HorarioApertura_CT.setEditor(new JSpinner.DateEditor(SP_HorarioApertura_CT, "hh:mm a"));
        JD_Crear_Tienda.getContentPane().add(SP_HorarioApertura_CT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 90, -1));
        new SpinnerDateModel(new java.util.Date(), null, null, Calendar.HOUR);

        SP_HorarioCierre_CT.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1672596000000L), null, null, java.util.Calendar.DAY_OF_MONTH));
        SP_HorarioCierre_CT.setEditor(new JSpinner.DateEditor(SP_HorarioCierre_CT, "hh:mm a")
        );
        JD_Crear_Tienda.getContentPane().add(SP_HorarioCierre_CT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 90, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("-");
        JD_Crear_Tienda.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 40, 20));

        JD_Modificar_Tienda.setMinimumSize(new java.awt.Dimension(600, 340));
        JD_Modificar_Tienda.setResizable(false);
        JD_Modificar_Tienda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Modificar Tienda");
        JD_Modificar_Tienda.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));
        JD_Modificar_Tienda.getContentPane().add(TF_Nombre_MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, -1));

        jLabel23.setText("Horario");
        JD_Modificar_Tienda.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, 20));

        BT_Crear_CC2.setText("Crear");
        JD_Modificar_Tienda.getContentPane().add(BT_Crear_CC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 110, -1));

        jLabel24.setText("Nombre");
        JD_Modificar_Tienda.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, 20));

        CB_Ubicacion_MT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Modificar_Tienda.getContentPane().add(CB_Ubicacion_MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, -1));

        jLabel25.setText("Ubicación");
        JD_Modificar_Tienda.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 20));

        SP_HorarioApertura_MT.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1672552800000L), null, null, java.util.Calendar.HOUR));
        SP_HorarioApertura_MT.setToolTipText("");
        SP_HorarioApertura_MT.setEditor(new JSpinner.DateEditor(SP_HorarioApertura_MT, "hh:mm a"));
        JD_Modificar_Tienda.getContentPane().add(SP_HorarioApertura_MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 90, -1));
        new SpinnerDateModel(new java.util.Date(), null, null, Calendar.HOUR);

        SP_HorarioCierre_MT.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1672596000000L), null, null, java.util.Calendar.DAY_OF_MONTH));
        SP_HorarioCierre_MT.setEditor(new JSpinner.DateEditor(SP_HorarioCierre_MT, "hh:mm a")
        );
        JD_Modificar_Tienda.getContentPane().add(SP_HorarioCierre_MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 90, -1));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("-");
        JD_Modificar_Tienda.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 40, 20));

        JD_Eliminar_Tienda.setMinimumSize(new java.awt.Dimension(600, 300));
        JD_Eliminar_Tienda.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Eliminar Tienda");
        JD_Eliminar_Tienda.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));

        jLabel16.setText("Tienda");
        JD_Eliminar_Tienda.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        BT_Eliminar_ET.setText("Eliminar");
        JD_Eliminar_Tienda.getContentPane().add(BT_Eliminar_ET, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        CB_Tienda_ET.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD_Eliminar_Tienda.getContentPane().add(CB_Tienda_ET, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(90, 50));
        setMinimumSize(new java.awt.Dimension(1362, 830));
        setPreferredSize(new java.awt.Dimension(1362, 830));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        Tab_Administrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A_Productos.setBackground(new java.awt.Color(153, 0, 0));
        A_Productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos");
        jLabel1.setToolTipText("");
        A_Productos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1350, -1));

        A_BT_Crear_Productos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Crear_Productos.setText("Crear");
        A_BT_Crear_Productos.setBorderPainted(false);
        A_Productos.add(A_BT_Crear_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 200, 130));

        A_BT_Modificar_Productos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Modificar_Productos.setText("Modificar");
        A_BT_Modificar_Productos.setBorderPainted(false);
        A_Productos.add(A_BT_Modificar_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 200, 130));

        A_BT_Eliminar_Productos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Eliminar_Productos.setText("Eliminar");
        A_BT_Eliminar_Productos.setBorderPainted(false);
        A_Productos.add(A_BT_Eliminar_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 200, 130));

        Tab_Administrar.add(A_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1360, 270));

        A_Tiendas.setBackground(new java.awt.Color(102, 102, 0));
        A_Tiendas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tiendas");
        jLabel2.setToolTipText("");
        A_Tiendas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1350, -1));

        A_BT_Eliminar_Tiendas.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Eliminar_Tiendas.setText("Eliminar");
        A_BT_Eliminar_Tiendas.setBorderPainted(false);
        A_Tiendas.add(A_BT_Eliminar_Tiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 200, 130));

        A_BT_Modificar_Tiendas.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Modificar_Tiendas.setText("Modificar");
        A_BT_Modificar_Tiendas.setBorderPainted(false);
        A_Tiendas.add(A_BT_Modificar_Tiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 200, 130));

        A_BT_Crear_Tiendas.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Crear_Tiendas.setText("Crear");
        A_BT_Crear_Tiendas.setBorderPainted(false);
        A_Tiendas.add(A_BT_Crear_Tiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 200, 130));

        Tab_Administrar.add(A_Tiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 270));

        A_Clientes.setBackground(new java.awt.Color(0, 153, 0));
        A_Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Clientes");
        jLabel3.setToolTipText("");
        A_Clientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1350, -1));

        A_BT_Eliminar_Clientes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Eliminar_Clientes.setText("Eliminar");
        A_BT_Eliminar_Clientes.setBorderPainted(false);
        A_Clientes.add(A_BT_Eliminar_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 200, 130));

        A_BT_Crear_Clientes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Crear_Clientes.setText("Crear");
        A_BT_Crear_Clientes.setBorderPainted(false);
        A_Clientes.add(A_BT_Crear_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 200, 130));

        A_BT_Modificar_Clientes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        A_BT_Modificar_Clientes.setText("Modificar");
        A_BT_Modificar_Clientes.setBorderPainted(false);
        A_Clientes.add(A_BT_Modificar_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 200, 130));

        Tab_Administrar.add(A_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1360, 270));

        Tabs.addTab("Administrar", Tab_Administrar);

        Tab_Tiendas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T_Panel_Botones.setBackground(new java.awt.Color(33, 33, 33));
        T_Panel_Botones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        T_Panel_Botones.add(T_Decor_BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1120, -1));

        Decor_Sep_1.setBackground(new java.awt.Color(0, 51, 102));
        Decor_Sep_1.setForeground(new java.awt.Color(0, 102, 255));
        Decor_Sep_1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Decor_Sep_1.setOpaque(true);
        T_Panel_Botones.add(Decor_Sep_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        Decor_Sep_3.setBackground(new java.awt.Color(0, 51, 102));
        Decor_Sep_3.setForeground(new java.awt.Color(0, 102, 255));
        Decor_Sep_3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Decor_Sep_3.setOpaque(true);
        T_Panel_Botones.add(Decor_Sep_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 10, 40));

        Decor_Sep_4.setBackground(new java.awt.Color(0, 51, 102));
        Decor_Sep_4.setForeground(new java.awt.Color(0, 102, 255));
        Decor_Sep_4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Decor_Sep_4.setOpaque(true);
        T_Panel_Botones.add(Decor_Sep_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 10, 40));

        Decor_Sep_2.setBackground(new java.awt.Color(0, 51, 102));
        Decor_Sep_2.setForeground(new java.awt.Color(0, 102, 255));
        Decor_Sep_2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Decor_Sep_2.setOpaque(true);
        T_Panel_Botones.add(Decor_Sep_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 10, 40));

        BT_1.setBackground(new java.awt.Color(33, 33, 33));
        BT_1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        BT_1.setForeground(new java.awt.Color(204, 204, 204));
        BT_1.setText("Crear");
        BT_1.setBorder(null);
        BT_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BT_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_1MousePressed(evt);
            }
        });
        BT_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_1ActionPerformed(evt);
            }
        });
        T_Panel_Botones.add(BT_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        BT_3.setBackground(new java.awt.Color(33, 33, 33));
        BT_3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        BT_3.setForeground(new java.awt.Color(204, 204, 204));
        BT_3.setText("B3");
        BT_3.setBorder(null);
        BT_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BT_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_3MousePressed(evt);
            }
        });
        T_Panel_Botones.add(BT_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 40));

        BT_4.setBackground(new java.awt.Color(33, 33, 33));
        BT_4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        BT_4.setForeground(new java.awt.Color(204, 204, 204));
        BT_4.setText("B4");
        BT_4.setBorder(null);
        BT_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BT_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_4MousePressed(evt);
            }
        });
        T_Panel_Botones.add(BT_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 40));

        BT_2.setBackground(new java.awt.Color(33, 33, 33));
        BT_2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        BT_2.setForeground(new java.awt.Color(204, 204, 204));
        BT_2.setText("B2");
        BT_2.setBorder(null);
        BT_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BT_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_2MousePressed(evt);
            }
        });
        BT_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_2ActionPerformed(evt);
            }
        });
        T_Panel_Botones.add(BT_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 40));
        T_Panel_Botones.add(T_Decor_BarraSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1120, 50));

        Tab_Tiendas.add(T_Panel_Botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 740));

        T_Panel_Inventario.setBackground(new java.awt.Color(204, 204, 255));
        T_Panel_Inventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Tab_Tiendas.add(T_Panel_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 1200, 740));

        Tabs.addTab("Tiendas", Tab_Tiendas);

        Tab_Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Tabs.addTab("Clientes", Tab_Clientes);

        Tab_Productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Tabs.addTab("Productos", Tab_Productos);

        getContentPane().add(Tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_2ActionPerformed

    }//GEN-LAST:event_BT_2ActionPerformed

    private void BT_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_2MousePressed

    }//GEN-LAST:event_BT_2MousePressed

    private void BT_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_4MousePressed

    }//GEN-LAST:event_BT_4MousePressed

    private void BT_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_3MousePressed

    }//GEN-LAST:event_BT_3MousePressed

    private void BT_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_1ActionPerformed

    }//GEN-LAST:event_BT_1ActionPerformed

    private void BT_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_1MousePressed
        /*
        T_ColorChange_Ventanas(BT_1, Decor_Sep_1,
            BT_3, BT_2, BT_4,
            Decor_Sep_2, Decor_Sep_3, Decor_Sep_4
        );
        BD_Visible_Panel1();
        */
    }//GEN-LAST:event_BT_1MousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_BT_Crear_Clientes;
    private javax.swing.JButton A_BT_Crear_Productos;
    private javax.swing.JButton A_BT_Crear_Tiendas;
    private javax.swing.JButton A_BT_Eliminar_Clientes;
    private javax.swing.JButton A_BT_Eliminar_Productos;
    private javax.swing.JButton A_BT_Eliminar_Tiendas;
    private javax.swing.JButton A_BT_Modificar_Clientes;
    private javax.swing.JButton A_BT_Modificar_Productos;
    private javax.swing.JButton A_BT_Modificar_Tiendas;
    private javax.swing.JPanel A_Clientes;
    private javax.swing.JPanel A_Productos;
    private javax.swing.JPanel A_Tiendas;
    private javax.swing.JButton BT_1;
    private javax.swing.JButton BT_2;
    private javax.swing.JButton BT_3;
    private javax.swing.JButton BT_4;
    private javax.swing.JButton BT_Crear_CC;
    private javax.swing.JButton BT_Crear_CC1;
    private javax.swing.JButton BT_Crear_CC2;
    private javax.swing.JButton BT_Eliminar_EC;
    private javax.swing.JButton BT_Eliminar_ET;
    private javax.swing.JButton BT_Modificar_MC;
    private javax.swing.JComboBox<String> CB_Cliente_EC;
    private javax.swing.JComboBox<String> CB_Tienda_ET;
    private javax.swing.JComboBox<String> CB_Ubicacion_CT;
    private javax.swing.JComboBox<String> CB_Ubicacion_MT;
    private javax.swing.JSeparator Decor_Sep_1;
    private javax.swing.JSeparator Decor_Sep_2;
    private javax.swing.JSeparator Decor_Sep_3;
    private javax.swing.JSeparator Decor_Sep_4;
    private javax.swing.JDialog JD_Crear_Cliente;
    private javax.swing.JDialog JD_Crear_Tienda;
    private javax.swing.JDialog JD_Eliminar_Cliente;
    private javax.swing.JDialog JD_Eliminar_Tienda;
    private javax.swing.JDialog JD_Modificar_Cliente;
    private javax.swing.JDialog JD_Modificar_Tienda;
    private javax.swing.JSpinner SP_HorarioApertura_CT;
    private javax.swing.JSpinner SP_HorarioApertura_MT;
    private javax.swing.JSpinner SP_HorarioCierre_CT;
    private javax.swing.JSpinner SP_HorarioCierre_MT;
    private javax.swing.JTextField TF_Correo_CC;
    private javax.swing.JTextField TF_Correo_MC;
    private javax.swing.JTextField TF_Nombre_CC;
    private javax.swing.JTextField TF_Nombre_CT;
    private javax.swing.JTextField TF_Nombre_MC;
    private javax.swing.JTextField TF_Nombre_MT;
    private javax.swing.JLabel T_Decor_BarraSuperior;
    private javax.swing.JLabel T_Decor_BarraSuperior1;
    private javax.swing.JPanel T_Panel_Botones;
    private javax.swing.JPanel T_Panel_Inventario;
    private javax.swing.JPanel Tab_Administrar;
    private javax.swing.JPanel Tab_Clientes;
    private javax.swing.JPanel Tab_Productos;
    private javax.swing.JPanel Tab_Tiendas;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
